# -*- coding: utf-8 -*-
TRUMP=[
("GAZA","lemonde.fr","Bande de Gaza : Donald Trump annonce un accord sur le désarmement du Hamas"),
("GAZA","nouvelobs.com","Ce que prévoit l'accord sur les armes du Hamas, annoncé par Donald Trump"),
("GAZA","lemonde.fr","Donald Trump annonce le désarmement du Hamas par un « accord historique » aux contours flous"),
("GAZA","cnews.fr","Donald Trump annonce un accord sur le «désarmement complet» du Hamas à Gaza"),
("GAZA","la-croix.com","Gaza : Donald Trump annonce un « accord pour une paix durable » avec le Hamas, Israël renâcle"),
("GAZA","ouest-france.fr","Gaza : Trump annonce un accord « historique » pour le désarmement du Hamas"),
("GAZA","liberation.fr","Gaza : Trump annonce un accord sur le désarmement du Hamas, Nétanyahou muré dans le silence"),
("GAZA","bfmtv.com","Gaza: que prévoit l'accord sur le désarmement du Hamas annoncé par Donald Trump?"),
("GAZA","humanite.fr","Génocide à Gaza : Donald Trump annonce un accord sur le retrait des forces d'occupation israélienne et le désarmement du Hamas"),
("UKRAINE","bfmtv.com","\"Nous devons faire preuve d'une certaine prudence\": Donald Trump \"n'est pas certain\" qu'il laissera l'Ukraine produire des missiles Patriot"),
("UKRAINE","lemonde.fr","EN DIRECT, guerre en Ukraine : Donald Trump affirme ne pas avoir décidé d'autoriser la production de missiles Patriot en Ukraine"),
("UKRAINE","cnews.fr","Guerre en Ukraine : Donald Trump finalement «pas sûr» d'accorder son feu vert à Kiev pour fabriquer des missiles Patriot"),
("UKRAINE","ouest-france.fr","Guerre en Ukraine : Trump hésite sur les Patriot, Moscou met en garde les volontaires étrangers... Le point sur la nuit"),
("UKRAINE","la-croix.com","Guerre en Ukraine : Varsovie convoque l'ambassadeur russe ; Trump réticent à aider Kiev"),
("IRAN","courrierinternational.com","Donald Trump “exaspéré” par les divisions de son administration sur la guerre en Iran"),
("IRAN","lemonde.fr","Face à Trump, l'Iran sort de la logique de représailles et cherche à reprendre la main sur le conflit"),
("IRAN","lemonde.fr","Guerre en Iran : la rhétorique belliciste de Donald Trump, reflet de l'enlisement américain"),
("USMISC","nytimes.com","After Claiming ‘Bias’ at Smithsonian, Trump Officials Stage Patriotic Exhibition"),
("USMISC","nytimes.com","Critics Say Historic Sites Are Endangered by Trump-Aligned Panel's Plan"),
("USMISC","nytimes.com","Defying Trump, Cornyn Uses His Lame-Duck Power"),
("USMISC","bfmtv.com","États-Unis: Donald Trump veut encourager les vétérans à devenir chauffeur routier"),
("USMISC","cnews.fr","Grand Nord : ce que l'on sait de la mission d'envergure lancée par la Chine et scrutée par Donald Trump"),
("USMISC","nytimes.com","How the Pro-Trump Media Ecosystem Is Splintering Ahead of the Midterms"),
("USMISC","nytimes.com","In Trump's Economy, Job Gains Go to Women. That's Not an Entirely Good Thing."),
]
