#!/bin/bash
# =============================================================================
# Script de vérification : Onboarding Thèmes First (Story 2.7)
# =============================================================================
#
# OBJECTIF : Vérifier que l'ordre de Section 3 est inversé et que la
#            pré-sélection des sources fonctionne correctement.
#
# PRÉREQUIS :
#   - App mobile compilée et lancée
#   - Nouveau compte utilisateur (ou reset onboarding via Settings)
#
# =============================================================================

echo "=================================================="
echo "  VERIFICATION : Onboarding Themes First (2.7)"
echo "=================================================="
echo ""

echo "=== TEST 1: Ordre des questions Section 3 ==="
echo ""
echo "  1. Lancer l'app et créer un nouveau compte"
echo "  2. Compléter Sections 1 et 2 normalement"
echo "  3. Arriver à Section 3"
echo ""
echo "  ✅ ATTENDU : La première question de Section 3 est THEMES (Q9)"
echo "              - Titre: 'Quels sont vos centres d'intérêt ?'"
echo "              - Chips de thèmes avec sous-thèmes expansibles"
echo ""
echo "  4. Sélectionner 2-3 thèmes (ex: Tech, Science, International)"
echo "  5. Appuyer sur 'Continuer'"
echo ""
echo "  ✅ ATTENDU : L'écran suivant est SOURCES (Q10)"
echo "              - Titre: 'Construisons votre front de sources fiables.'"
echo ""
read -p "Appuyez sur Entrée pour continuer..."

echo ""
echo "=== TEST 2: Pré-sélection des sources ==="
echo ""
echo "  Sur l'écran Sources (Q10) :"
echo ""
echo "  ✅ ATTENDU 1 : Message informatif visible en haut"
echo "                 '💡 Pré-sélection basée sur vos thèmes'"
echo ""
echo "  ✅ ATTENDU 2 : Plusieurs sources sont PRÉ-COCHÉES"
echo "                 (chips avec bordure terracotta)"
echo ""
echo "  ✅ ATTENDU 3 : Les sources pré-sélectionnées correspondent aux thèmes"
echo "                 Ex: Tech → ScienceEtonnante, Epsiloon, etc."
echo "                 Ex: International → Le Dessous des Cartes, etc."
echo ""
read -p "Appuyez sur Entrée pour continuer..."

echo ""
echo "=== TEST 3: Modification de la pré-sélection ==="
echo ""
echo "  1. Décocher une source pré-sélectionnée (tap sur une chip cochée)"
echo "  2. Cocher une nouvelle source non pré-sélectionnée"
echo ""
echo "  ✅ ATTENDU : Les modifications sont prises en compte"
echo "              Le bouton 'Continuer (X sélectionnés)' se met à jour"
echo ""
echo "  3. Appuyer sur 'Continuer'"
echo "  4. Sur l'écran Finalize, appuyer sur 'Créer mon flux'"
echo "  5. Attendre l'animation de conclusion"
echo ""
echo "  ✅ ATTENDU : Arrivée sur le Feed personnalisé"
echo "              Les sources sélectionnées sont utilisées"
echo ""
read -p "Appuyez sur Entrée pour continuer..."

echo ""
echo "=== TEST 4: Navigation retour (Back) ==="
echo ""
echo "  1. Refaire l'onboarding (via Settings > Refaire l'onboarding)"
echo "  2. Arriver à l'écran Sources (Q10)"
echo "  3. Appuyer sur le bouton Retour (flèche en haut à gauche)"
echo ""
echo "  ✅ ATTENDU 1 : Retour sur l'écran Thèmes (Q9)"
echo "  ✅ ATTENDU 2 : Les thèmes précédemment sélectionnés sont TOUJOURS cochés"
echo ""
echo "  4. Revenir sur l'écran Sources"
echo ""
echo "  ✅ ATTENDU 3 : La pré-sélection est conservée"
echo ""
read -p "Appuyez sur Entrée pour continuer..."

echo ""
echo "=== TEST 5: Sauvegarde backend ==="
echo ""
echo "  1. Compléter l'onboarding avec des thèmes et sources spécifiques"
echo "  2. Ouvrir les DevTools backend ou Supabase Dashboard"
echo "  3. Vérifier la table 'user_interests'"
echo ""
echo "  ✅ ATTENDU : Les thèmes sélectionnés sont enregistrés"
echo ""
echo "  4. Vérifier la table 'user_sources' (ou preferred_sources dans profil)"
echo ""
echo "  ✅ ATTENDU : Les sources sélectionnées (finales) sont enregistrées"
echo ""

echo ""
echo "=================================================="
echo "  RÉSUMÉ DE LA VÉRIFICATION"
echo "=================================================="
echo ""
echo "  Si tous les tests passent :"
echo "  ✅ Story 2.7 implémentée correctement"
echo ""
echo "  Si un test échoue :"
echo "  ❌ Documenter le problème dans docs/bugs/"
echo "  ❌ Créer une issue avec les détails"
echo ""
echo "=================================================="
