"""add_fqs_scores_to_sources

Revision ID: ce8cff0c3c5d
Revises: enable_pg_trgm
Create Date: 2026-01-12 18:37:09.120804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8cff0c3c5d'
down_revision: Union[str, Sequence[str], None] = 'enable_pg_trgm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_title_trgm'), table_name='contents', postgresql_using='gin')
    op.add_column('sources', sa.Column('score_independence', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('score_rigor', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('score_ux', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'score_ux')
    op.drop_column('sources', 'score_rigor')
    op.drop_column('sources', 'score_independence')
    op.create_index(op.f('ix_contents_title_trgm'), 'contents', ['title'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
