"""split_status_saved_hidden

Revision ID: e9ae8866ece2
Revises: 399aa710ae34
Create Date: 2026-01-11 19:28:20.819500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ae8866ece2'
down_revision: Union[str, Sequence[str], None] = '399aa710ae34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content_status', sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_content_status', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_user_content_status_content_id'), table_name='user_content_status')
    op.drop_index(op.f('ix_user_content_status_status'), table_name='user_content_status')
    op.drop_index(op.f('ix_user_content_status_user_id'), table_name='user_content_status')
    op.drop_index(op.f('ix_user_sources_user_id'), table_name='user_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_sources_user_id'), 'user_sources', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_content_status_user_id'), 'user_content_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_content_status_status'), 'user_content_status', ['status'], unique=False)
    op.create_index(op.f('ix_user_content_status_content_id'), 'user_content_status', ['content_id'], unique=False)
    op.drop_column('user_content_status', 'is_hidden')
    op.drop_column('user_content_status', 'is_saved')
    # ### end Alembic commands ###
