"""Add performance indexes for digest endpoint optimization

Revision ID: x8y9z0a1b2c3
Revises: 4d497ce7bcc2
Create Date: 2026-02-02 02:00:00.000000

These indexes optimize the GET /api/digest endpoint which was timing out
with connectionTimeout > 10s.

Key optimizations:
1. Composite index on (source_id, published_at DESC) for Content queries
2. Partial index on curated sources for Emergency Fallback
3. Composite index on UserContentStatus for exclusion queries
4. Index on Source.theme for muted theme filtering

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'x8y9z0a1b2c3'
down_revision: Union[str, Sequence[str], None] = '4d497ce7bcc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add performance indexes for digest queries."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Composite index for Content queries ordered by published_at
    # Used in: _get_candidates() for fallback queries ordering by published_at
    op.create_index(
        'ix_contents_source_published',
        'contents', 
        ['source_id', sa.literal_column('published_at DESC')],
        unique=False
    )
    
    # 2. Partial index for Emergency Fallback on curated sources
    # Used in: _get_emergency_candidates() which filters Source.is_curated == True
    # The index includes source_id to support the join with Source table
    op.create_index(
        'ix_contents_curated_published',
        'contents',
        [sa.literal_column('published_at DESC'), 'source_id'],
        unique=False,
        postgresql_where=sa.text("source_id IN (SELECT id FROM sources WHERE is_curated = true)")
    )
    
    # 3. Composite index for UserContentStatus exclusion queries
    # Used in: _get_candidates() for the EXISTS subquery that excludes content
    # The query filters on user_id AND checks is_hidden, is_saved, status
    op.create_index(
        'ix_user_content_status_exclusion',
        'user_content_status',
        ['user_id', 'content_id', 'is_hidden', 'is_saved', 'status'],
        unique=False
    )
    
    # 4. Index on Source.theme for muted theme filtering
    # Used in: _get_candidates() to filter out muted themes
    op.create_index(
        'ix_sources_theme',
        'sources',
        ['theme'],
        unique=False
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove performance indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_theme', table_name='sources')
    op.drop_index('ix_user_content_status_exclusion', table_name='user_content_status')
    op.drop_index('ix_contents_curated_published', table_name='contents')
    op.drop_index('ix_contents_source_published', table_name='contents')
    # ### end Alembic commands ###
