"""Routers API."""

from app.routers import (
    admin_cohorts,
    analytics,
    app_update,
    auth,
    collections,
    contents,
    custom_topics,
    digest,
    feed,
    internal,
    personalization,
    progress,
    sources,
    streaks,
    subscription,
    users,
    veille,
    webhooks,
)

__all__ = [
    "admin_cohorts",
    "analytics",
    "app_update",
    "auth",
    "collections",
    "contents",
    "custom_topics",
    "digest",
    "feed",
    "internal",
    "personalization",
    "progress",
    "sources",
    "streaks",
    "subscription",
    "users",
    "veille",
    "webhooks",
]
