-- Sanitized prod schema snapshot — see sanitize.py for what was stripped.
-- Generated by packages/api/alembic/baseline/sanitize.py

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

--
-- PostgreSQL database dump
--

\restrict jf8K4albLtfvG21T3Ds57jSrwBEFDBbL8IdtDJoU6RcU58WoQhkdax4gXbstdT2

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.9 (Homebrew)

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;

--
-- Name: update_collections_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_collections_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

--
-- Name: analytics_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analytics_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    event_type character varying(50) NOT NULL,
    event_data jsonb DEFAULT '{}'::jsonb NOT NULL,
    device_id character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: app_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_config (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: article_feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_feedback (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    content_id uuid NOT NULL,
    sentiment character varying(10) NOT NULL,
    reasons text[],
    comment text,
    digest_date date,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: classification_queue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classification_queue (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    content_id uuid NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone
);

--
-- Name: collection_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collection_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    collection_id uuid NOT NULL,
    content_id uuid NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    is_liked_collection boolean DEFAULT false NOT NULL
);

--
-- Name: contents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contents (
    id uuid NOT NULL,
    source_id uuid NOT NULL,
    title character varying(500) NOT NULL,
    url text NOT NULL,
    thumbnail_url text,
    description text,
    published_at timestamp with time zone NOT NULL,
    duration_seconds integer,
    content_type character varying(20) NOT NULL,
    guid character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cluster_id uuid,
    html_content text,
    audio_url text,
    topics text[],
    theme character varying(50),
    is_paid boolean DEFAULT false,
    content_quality character varying(20) DEFAULT NULL::character varying,
    extraction_attempted_at timestamp with time zone,
    is_serene boolean,
    entities text[],
    is_good_news boolean
);

--
-- Name: curation_annotations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.curation_annotations (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    content_id uuid NOT NULL,
    feed_date date NOT NULL,
    label character varying(10) NOT NULL,
    note text,
    annotated_by character varying(50) DEFAULT 'admin'::character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_curation_label CHECK (((label)::text = ANY ((ARRAY['good'::character varying, 'bad'::character varying, 'missing'::character varying])::text[])))
);

--
-- Name: daily_digest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_digest (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    target_date date NOT NULL,
    items jsonb DEFAULT '[]'::jsonb NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    mode character varying(30) DEFAULT 'pour_vous'::character varying,
    format_version character varying(20) DEFAULT 'flat_v1'::character varying,
    is_serene boolean DEFAULT false NOT NULL
);

--
-- Name: daily_top3; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_top3 (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    content_id uuid NOT NULL,
    rank integer NOT NULL,
    top3_reason character varying(100) NOT NULL,
    consumed boolean DEFAULT false NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT daily_top3_rank_check CHECK (((rank >= 1) AND (rank <= 3)))
);

--
-- Name: digest_completions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.digest_completions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    target_date date NOT NULL,
    completed_at timestamp with time zone DEFAULT now() NOT NULL,
    articles_read integer DEFAULT 0 NOT NULL,
    articles_saved integer DEFAULT 0 NOT NULL,
    articles_dismissed integer DEFAULT 0 NOT NULL,
    closure_time_seconds integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: digest_generation_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.digest_generation_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    target_date date NOT NULL,
    is_serene boolean DEFAULT false NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    last_error text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: editorial_highlights_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.editorial_highlights_history (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind character varying(20) NOT NULL,
    content_id uuid NOT NULL,
    target_date date NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: failed_source_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.failed_source_attempts (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    input_text character varying(500) NOT NULL,
    input_type character varying(20) NOT NULL,
    endpoint character varying(20) NOT NULL,
    error_message text,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: nps_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nps_responses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    score smallint NOT NULL,
    comment text,
    campaign_id text DEFAULT 'default'::text NOT NULL,
    source text DEFAULT 'email'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT nps_responses_score_check CHECK (((score >= 0) AND (score <= 10)))
);

--
-- Name: perspective_analyses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.perspective_analyses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    content_id uuid NOT NULL,
    analysis_text text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: serene_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.serene_reports (
    id uuid NOT NULL,
    content_id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: source_search_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_search_cache (
    query_hash character varying(64) NOT NULL,
    query_raw text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);

--
-- Name: source_search_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_search_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    query_raw character varying(500) NOT NULL,
    query_normalized character varying(500) NOT NULL,
    content_type character varying(20),
    expand boolean DEFAULT false NOT NULL,
    layers_called text[] DEFAULT '{}'::text[] NOT NULL,
    result_count integer DEFAULT 0 NOT NULL,
    top_results jsonb DEFAULT '[]'::jsonb NOT NULL,
    latency_ms integer DEFAULT 0 NOT NULL,
    cache_hit boolean DEFAULT false NOT NULL,
    abandoned boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    id uuid NOT NULL,
    name character varying(200) NOT NULL,
    url text NOT NULL,
    feed_url text NOT NULL,
    type character varying(20) NOT NULL,
    theme character varying(50) NOT NULL,
    description text,
    logo_url text,
    is_curated boolean NOT NULL,
    is_active boolean NOT NULL,
    last_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    bias_stance character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    reliability_score character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    bias_origin character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    score_independence double precision,
    score_rigor double precision,
    score_ux double precision,
    granular_topics text[],
    une_feed_url text,
    secondary_themes text[],
    paywall_config jsonb,
    source_tier character varying(20) DEFAULT 'mainstream'::character varying NOT NULL,
    tone character varying(20),
    serein_default boolean DEFAULT false NOT NULL,
    is_pepite_recommendation boolean DEFAULT false NOT NULL,
    pepite_for_themes text[],
    recommended_by character varying(50),
    recommendation_reason text,
    CONSTRAINT ck_source_theme_valid CHECK (((theme)::text = ANY ((ARRAY['tech'::character varying, 'society'::character varying, 'environment'::character varying, 'economy'::character varying, 'politics'::character varying, 'culture'::character varying, 'science'::character varying, 'international'::character varying, 'custom'::character varying, 'sport'::character varying])::text[])))
);

--
-- Name: topic_quizzes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topic_quizzes (
    id uuid NOT NULL,
    topic character varying(100) NOT NULL,
    question text NOT NULL,
    options jsonb NOT NULL,
    correct_answer integer NOT NULL,
    difficulty integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: user_content_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_content_status (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    content_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    seen_at timestamp with time zone,
    time_spent_seconds integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_saved boolean DEFAULT false NOT NULL,
    is_hidden boolean DEFAULT false NOT NULL,
    hidden_reason character varying,
    saved_at timestamp with time zone,
    is_liked boolean DEFAULT false NOT NULL,
    liked_at timestamp with time zone,
    note_text text,
    note_updated_at timestamp with time zone,
    last_impressed_at timestamp with time zone,
    manually_impressed boolean DEFAULT false NOT NULL,
    reading_progress smallint DEFAULT '0'::smallint NOT NULL
);

--
-- Name: user_entity_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_entity_preferences (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    entity_canonical text NOT NULL,
    preference character varying(10) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: user_interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_interests (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    interest_slug character varying(50) NOT NULL,
    weight double precision NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: user_letter_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_letter_progress (
    user_id uuid NOT NULL,
    letter_id text NOT NULL,
    status text NOT NULL,
    completed_actions jsonb DEFAULT '[]'::jsonb NOT NULL,
    started_at timestamp with time zone,
    archived_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_user_letter_progress_status CHECK ((status = ANY (ARRAY['upcoming'::text, 'active'::text, 'archived'::text])))
);

--
-- Name: user_notification_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notification_preferences (
    user_id uuid NOT NULL,
    push_enabled boolean DEFAULT false NOT NULL,
    preset text DEFAULT 'minimaliste'::text NOT NULL,
    time_slot text DEFAULT 'morning'::text NOT NULL,
    timezone text DEFAULT 'Europe/Paris'::text NOT NULL,
    refusal_count integer DEFAULT 0 NOT NULL,
    last_refusal_at timestamp with time zone,
    last_renudge_at timestamp with time zone,
    renudge_shown_count integer DEFAULT 0 NOT NULL,
    modal_seen boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    notif_veille_enabled boolean DEFAULT false NOT NULL,
    CONSTRAINT user_notif_prefs_preset_check CHECK ((preset = ANY (ARRAY['minimaliste'::text, 'curieux'::text]))),
    CONSTRAINT user_notif_prefs_time_slot_check CHECK ((time_slot = ANY (ARRAY['morning'::text, 'evening'::text])))
);

--
-- Name: user_personalization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_personalization (
    user_id uuid NOT NULL,
    muted_sources uuid[] DEFAULT '{}'::uuid[] NOT NULL,
    muted_themes text[] DEFAULT '{}'::text[] NOT NULL,
    muted_topics text[] DEFAULT '{}'::text[] NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    muted_content_types text[] DEFAULT '{}'::text[],
    hide_paid_content boolean DEFAULT true,
    pepite_carousel_dismissed_at timestamp with time zone,
    pepite_carousel_last_shown_at timestamp with time zone
);

--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    preference_key character varying(50) NOT NULL,
    preference_value character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    display_name character varying(100),
    age_range character varying(10),
    gender character varying(20),
    onboarding_completed boolean NOT NULL,
    gamification_enabled boolean NOT NULL,
    weekly_goal integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: user_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sources (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    source_id uuid NOT NULL,
    is_custom boolean NOT NULL,
    added_at timestamp with time zone NOT NULL,
    priority_multiplier double precision DEFAULT '1'::double precision NOT NULL,
    has_subscription boolean DEFAULT false NOT NULL
);

--
-- Name: user_streaks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_streaks (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    current_streak integer NOT NULL,
    longest_streak integer NOT NULL,
    last_activity_date date,
    weekly_count integer NOT NULL,
    week_start date,
    updated_at timestamp with time zone NOT NULL,
    closure_streak integer DEFAULT 0 NOT NULL,
    longest_closure_streak integer DEFAULT 0 NOT NULL,
    last_closure_date date
);

--
-- Name: user_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_subscriptions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    revenuecat_user_id character varying(200),
    status character varying(20) NOT NULL,
    product_id character varying(100),
    trial_start timestamp with time zone NOT NULL,
    trial_end timestamp with time zone NOT NULL,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: user_subtopics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_subtopics (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    topic_slug character varying(50) NOT NULL,
    weight double precision DEFAULT 1.0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: user_topic_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_topic_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    topic_name character varying(200) NOT NULL,
    slug_parent character varying(50) NOT NULL,
    keywords text[],
    intent_description text,
    source_type character varying(20) DEFAULT 'explicit'::character varying NOT NULL,
    priority_multiplier double precision DEFAULT 1.0 NOT NULL,
    composite_score double precision DEFAULT 0.0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    entity_type character varying(20) DEFAULT NULL::character varying,
    canonical_name character varying(200) DEFAULT NULL::character varying,
    excluded_from_serein boolean DEFAULT false NOT NULL
);

--
-- Name: user_topic_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_topic_progress (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    topic character varying(100) NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    points integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: user_well_informed_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_well_informed_ratings (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    score integer NOT NULL,
    context character varying(32) DEFAULT 'digest_inline'::character varying NOT NULL,
    device_id character varying(255),
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_well_informed_ratings_score_range CHECK (((score >= 1) AND (score <= 10)))
);

--
-- Name: veille_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veille_configs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    theme_id character varying(50) NOT NULL,
    theme_label character varying(120) NOT NULL,
    frequency character varying(20) NOT NULL,
    day_of_week smallint,
    delivery_hour smallint DEFAULT 7 NOT NULL,
    timezone text DEFAULT 'Europe/Paris'::text NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    last_delivered_at timestamp with time zone,
    next_scheduled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    purpose text,
    purpose_other text,
    editorial_brief text,
    preset_id text
);

--
-- Name: veille_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veille_deliveries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    veille_config_id uuid NOT NULL,
    target_date date NOT NULL,
    items jsonb DEFAULT '[]'::jsonb NOT NULL,
    generation_state character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    attempts smallint DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    last_error text,
    version smallint DEFAULT 1 NOT NULL,
    generated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: veille_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veille_sources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    veille_config_id uuid NOT NULL,
    source_id uuid NOT NULL,
    kind character varying(20) NOT NULL,
    why text,
    "position" smallint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: veille_topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.veille_topics (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    veille_config_id uuid NOT NULL,
    topic_id character varying(80) NOT NULL,
    label character varying(200) NOT NULL,
    kind character varying(20) NOT NULL,
    reason text,
    "position" smallint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: waitlist_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.waitlist_entries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    source character varying(50) DEFAULT 'landing'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    utm_source character varying(100),
    utm_medium character varying(100),
    utm_campaign character varying(100)
);

--
-- Name: waitlist_survey_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.waitlist_survey_responses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    waitlist_entry_id uuid NOT NULL,
    info_source character varying(100) NOT NULL,
    main_pain character varying(100) NOT NULL,
    pain_detail text,
    willingness character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);

--
-- Name: analytics_events analytics_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);

--
-- Name: app_config app_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_config
    ADD CONSTRAINT app_config_pkey PRIMARY KEY (key);

--
-- Name: article_feedback article_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_feedback
    ADD CONSTRAINT article_feedback_pkey PRIMARY KEY (id);

--
-- Name: classification_queue classification_queue_content_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classification_queue
    ADD CONSTRAINT classification_queue_content_id_key UNIQUE (content_id);

--
-- Name: classification_queue classification_queue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classification_queue
    ADD CONSTRAINT classification_queue_pkey PRIMARY KEY (id);

--
-- Name: collection_items collection_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_items
    ADD CONSTRAINT collection_items_pkey PRIMARY KEY (id);

--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);

--
-- Name: contents contents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contents
    ADD CONSTRAINT contents_pkey PRIMARY KEY (id);

--
-- Name: curation_annotations curation_annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curation_annotations
    ADD CONSTRAINT curation_annotations_pkey PRIMARY KEY (id);

--
-- Name: daily_digest daily_digest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_digest
    ADD CONSTRAINT daily_digest_pkey PRIMARY KEY (id);

--
-- Name: daily_top3 daily_top3_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_top3
    ADD CONSTRAINT daily_top3_pkey PRIMARY KEY (id);

--
-- Name: digest_completions digest_completions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.digest_completions
    ADD CONSTRAINT digest_completions_pkey PRIMARY KEY (id);

--
-- Name: digest_generation_state digest_generation_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.digest_generation_state
    ADD CONSTRAINT digest_generation_state_pkey PRIMARY KEY (id);

--
-- Name: editorial_highlights_history editorial_highlights_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.editorial_highlights_history
    ADD CONSTRAINT editorial_highlights_history_pkey PRIMARY KEY (id);

--
-- Name: failed_source_attempts failed_source_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.failed_source_attempts
    ADD CONSTRAINT failed_source_attempts_pkey PRIMARY KEY (id);

--
-- Name: nps_responses nps_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nps_responses
    ADD CONSTRAINT nps_responses_pkey PRIMARY KEY (id);

--
-- Name: nps_responses nps_responses_user_campaign_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nps_responses
    ADD CONSTRAINT nps_responses_user_campaign_unique UNIQUE (user_id, campaign_id);

--
-- Name: perspective_analyses perspective_analyses_content_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perspective_analyses
    ADD CONSTRAINT perspective_analyses_content_id_key UNIQUE (content_id);

--
-- Name: perspective_analyses perspective_analyses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perspective_analyses
    ADD CONSTRAINT perspective_analyses_pkey PRIMARY KEY (id);

--
-- Name: user_letter_progress pk_user_letter_progress; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_letter_progress
    ADD CONSTRAINT pk_user_letter_progress PRIMARY KEY (user_id, letter_id);

--
-- Name: serene_reports serene_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.serene_reports
    ADD CONSTRAINT serene_reports_pkey PRIMARY KEY (id);

--
-- Name: source_search_cache source_search_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_search_cache
    ADD CONSTRAINT source_search_cache_pkey PRIMARY KEY (query_hash);

--
-- Name: source_search_logs source_search_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_search_logs
    ADD CONSTRAINT source_search_logs_pkey PRIMARY KEY (id);

--
-- Name: sources sources_feed_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_feed_url_key UNIQUE (feed_url);

--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);

--
-- Name: topic_quizzes topic_quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topic_quizzes
    ADD CONSTRAINT topic_quizzes_pkey PRIMARY KEY (id);

--
-- Name: article_feedback uq_article_feedback_user_content; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_feedback
    ADD CONSTRAINT uq_article_feedback_user_content UNIQUE (user_id, content_id);

--
-- Name: collection_items uq_collection_item; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_items
    ADD CONSTRAINT uq_collection_item UNIQUE (collection_id, content_id);

--
-- Name: collections uq_collection_user_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT uq_collection_user_name UNIQUE (user_id, name);

--
-- Name: curation_annotations uq_curation_user_content_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curation_annotations
    ADD CONSTRAINT uq_curation_user_content_date UNIQUE (user_id, content_id, feed_date);

--
-- Name: daily_digest uq_daily_digest_user_date_serene; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_digest
    ADD CONSTRAINT uq_daily_digest_user_date_serene UNIQUE (user_id, target_date, is_serene);

--
-- Name: digest_completions uq_digest_completions_user_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.digest_completions
    ADD CONSTRAINT uq_digest_completions_user_date UNIQUE (user_id, target_date);

--
-- Name: digest_generation_state uq_digest_generation_state_user_date_variant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.digest_generation_state
    ADD CONSTRAINT uq_digest_generation_state_user_date_variant UNIQUE (user_id, target_date, is_serene);

--
-- Name: serene_reports uq_serene_report_user_content; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.serene_reports
    ADD CONSTRAINT uq_serene_report_user_content UNIQUE (user_id, content_id);

--
-- Name: user_content_status uq_user_content_status_user_content; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_content_status
    ADD CONSTRAINT uq_user_content_status_user_content UNIQUE (user_id, content_id);

--
-- Name: user_entity_preferences uq_user_entity_pref_user_entity; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entity_preferences
    ADD CONSTRAINT uq_user_entity_pref_user_entity UNIQUE (user_id, entity_canonical);

--
-- Name: user_sources uq_user_sources_user_source; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sources
    ADD CONSTRAINT uq_user_sources_user_source UNIQUE (user_id, source_id);

--
-- Name: user_topic_progress uq_user_topic_progress_user_topic; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_progress
    ADD CONSTRAINT uq_user_topic_progress_user_topic UNIQUE (user_id, topic);

--
-- Name: veille_deliveries uq_veille_deliveries_config_target; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_deliveries
    ADD CONSTRAINT uq_veille_deliveries_config_target UNIQUE (veille_config_id, target_date);

--
-- Name: veille_sources uq_veille_sources_config_source; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_sources
    ADD CONSTRAINT uq_veille_sources_config_source UNIQUE (veille_config_id, source_id);

--
-- Name: veille_topics uq_veille_topics_config_topic; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_topics
    ADD CONSTRAINT uq_veille_topics_config_topic UNIQUE (veille_config_id, topic_id);

--
-- Name: user_content_status user_content_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_content_status
    ADD CONSTRAINT user_content_status_pkey PRIMARY KEY (id);

--
-- Name: user_entity_preferences user_entity_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_entity_preferences
    ADD CONSTRAINT user_entity_preferences_pkey PRIMARY KEY (id);

--
-- Name: user_interests user_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT user_interests_pkey PRIMARY KEY (id);

--
-- Name: user_notification_preferences user_notification_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_preferences
    ADD CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (user_id);

--
-- Name: user_personalization user_personalization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_personalization
    ADD CONSTRAINT user_personalization_pkey PRIMARY KEY (user_id);

--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);

--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);

--
-- Name: user_profiles user_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);

--
-- Name: user_sources user_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sources
    ADD CONSTRAINT user_sources_pkey PRIMARY KEY (id);

--
-- Name: user_streaks user_streaks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_streaks
    ADD CONSTRAINT user_streaks_pkey PRIMARY KEY (id);

--
-- Name: user_streaks user_streaks_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_streaks
    ADD CONSTRAINT user_streaks_user_id_key UNIQUE (user_id);

--
-- Name: user_subscriptions user_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id);

--
-- Name: user_subscriptions user_subscriptions_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_user_id_key UNIQUE (user_id);

--
-- Name: user_subtopics user_subtopics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subtopics
    ADD CONSTRAINT user_subtopics_pkey PRIMARY KEY (id);

--
-- Name: user_topic_profiles user_topic_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_profiles
    ADD CONSTRAINT user_topic_profiles_pkey PRIMARY KEY (id);

--
-- Name: user_topic_progress user_topic_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_progress
    ADD CONSTRAINT user_topic_progress_pkey PRIMARY KEY (id);

--
-- Name: user_well_informed_ratings user_well_informed_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_well_informed_ratings
    ADD CONSTRAINT user_well_informed_ratings_pkey PRIMARY KEY (id);

--
-- Name: veille_configs veille_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_configs
    ADD CONSTRAINT veille_configs_pkey PRIMARY KEY (id);

--
-- Name: veille_deliveries veille_deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_deliveries
    ADD CONSTRAINT veille_deliveries_pkey PRIMARY KEY (id);

--
-- Name: veille_sources veille_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_sources
    ADD CONSTRAINT veille_sources_pkey PRIMARY KEY (id);

--
-- Name: veille_topics veille_topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_topics
    ADD CONSTRAINT veille_topics_pkey PRIMARY KEY (id);

--
-- Name: waitlist_entries waitlist_entries_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waitlist_entries
    ADD CONSTRAINT waitlist_entries_email_key UNIQUE (email);

--
-- Name: waitlist_entries waitlist_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waitlist_entries
    ADD CONSTRAINT waitlist_entries_pkey PRIMARY KEY (id);

--
-- Name: waitlist_survey_responses waitlist_survey_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waitlist_survey_responses
    ADD CONSTRAINT waitlist_survey_responses_pkey PRIMARY KEY (id);

--
-- Name: idx_entity_prefs_user_mute; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entity_prefs_user_mute ON public.user_entity_preferences USING btree (user_id) WHERE ((preference)::text = 'mute'::text);

--
-- Name: idx_entity_prefs_user_pref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entity_prefs_user_pref ON public.user_entity_preferences USING btree (user_id, preference);

--
-- Name: idx_queue_priority; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_queue_priority ON public.classification_queue USING btree (priority DESC, created_at);

--
-- Name: idx_queue_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_queue_status_created ON public.classification_queue USING btree (status, created_at);

--
-- Name: ix_analytics_events_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_analytics_events_created_at ON public.analytics_events USING btree (created_at);

--
-- Name: ix_analytics_events_event_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_analytics_events_event_type ON public.analytics_events USING btree (event_type);

--
-- Name: ix_analytics_events_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_analytics_events_user_id ON public.analytics_events USING btree (user_id);

--
-- Name: ix_article_feedback_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_article_feedback_content_id ON public.article_feedback USING btree (content_id);

--
-- Name: ix_collection_items_collection; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collection_items_collection ON public.collection_items USING btree (collection_id);

--
-- Name: ix_collection_items_content; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collection_items_content ON public.collection_items USING btree (content_id);

--
-- Name: ix_collections_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_collections_user_id ON public.collections USING btree (user_id);

--
-- Name: ix_contents_cluster_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_cluster_id ON public.contents USING btree (cluster_id);

--
-- Name: ix_contents_curated_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_curated_published ON public.contents USING btree (published_at DESC, source_id);

--
-- Name: ix_contents_entities; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_entities ON public.contents USING gin (entities);

--
-- Name: ix_contents_guid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_guid ON public.contents USING btree (guid);

--
-- Name: ix_contents_is_good_news; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_is_good_news ON public.contents USING btree (is_good_news) WHERE (is_good_news = true);

--
-- Name: ix_contents_published_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_published_at ON public.contents USING btree (published_at);

--
-- Name: ix_contents_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_source_id ON public.contents USING btree (source_id);

--
-- Name: ix_contents_source_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_source_published ON public.contents USING btree (source_id, published_at DESC);

--
-- Name: ix_contents_theme_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_contents_theme_published ON public.contents USING btree (theme, published_at DESC);

--
-- Name: ix_curation_annotations_feed_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_curation_annotations_feed_date ON public.curation_annotations USING btree (feed_date);

--
-- Name: ix_curation_annotations_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_curation_annotations_user_id ON public.curation_annotations USING btree (user_id);

--
-- Name: ix_daily_digest_generated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_digest_generated_at ON public.daily_digest USING btree (generated_at);

--
-- Name: ix_daily_digest_target_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_digest_target_date ON public.daily_digest USING btree (target_date);

--
-- Name: ix_daily_digest_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_digest_user_id ON public.daily_digest USING btree (user_id);

--
-- Name: ix_daily_top3_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_top3_user_date ON public.daily_top3 USING btree (user_id, generated_at);

--
-- Name: ix_daily_top3_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_daily_top3_user_id ON public.daily_top3 USING btree (user_id);

--
-- Name: ix_digest_completions_completed_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_digest_completions_completed_at ON public.digest_completions USING btree (completed_at);

--
-- Name: ix_digest_completions_target_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_digest_completions_target_date ON public.digest_completions USING btree (target_date);

--
-- Name: ix_digest_completions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_digest_completions_user_id ON public.digest_completions USING btree (user_id);

--
-- Name: ix_digest_generation_state_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_digest_generation_state_status ON public.digest_generation_state USING btree (status);

--
-- Name: ix_digest_generation_state_target_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_digest_generation_state_target_date ON public.digest_generation_state USING btree (target_date);

--
-- Name: ix_editorial_highlights_history_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_editorial_highlights_history_content_id ON public.editorial_highlights_history USING btree (content_id);

--
-- Name: ix_editorial_highlights_history_kind_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_editorial_highlights_history_kind_date ON public.editorial_highlights_history USING btree (kind, target_date);

--
-- Name: ix_failed_source_attempts_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_failed_source_attempts_created_at ON public.failed_source_attempts USING btree (created_at);

--
-- Name: ix_failed_source_attempts_input_text; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_failed_source_attempts_input_text ON public.failed_source_attempts USING btree (input_text);

--
-- Name: ix_failed_source_attempts_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_failed_source_attempts_user_id ON public.failed_source_attempts USING btree (user_id);

--
-- Name: ix_perspective_analyses_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_perspective_analyses_content_id ON public.perspective_analyses USING btree (content_id);

--
-- Name: ix_serene_reports_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_serene_reports_content_id ON public.serene_reports USING btree (content_id);

--
-- Name: ix_source_search_cache_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_source_search_cache_expires_at ON public.source_search_cache USING btree (expires_at);

--
-- Name: ix_source_search_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_source_search_logs_created_at ON public.source_search_logs USING btree (created_at);

--
-- Name: ix_source_search_logs_query_normalized; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_source_search_logs_query_normalized ON public.source_search_logs USING btree (query_normalized);

--
-- Name: ix_source_search_logs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_source_search_logs_user_id ON public.source_search_logs USING btree (user_id);

--
-- Name: ix_sources_is_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_is_active ON public.sources USING btree (is_active);

--
-- Name: ix_sources_is_curated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_is_curated ON public.sources USING btree (is_curated);

--
-- Name: ix_sources_is_pepite_recommendation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_is_pepite_recommendation ON public.sources USING btree (is_pepite_recommendation);

--
-- Name: ix_sources_secondary_themes; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_secondary_themes ON public.sources USING gin (secondary_themes);

--
-- Name: ix_sources_theme; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sources_theme ON public.sources USING btree (theme);

--
-- Name: ix_topic_quizzes_topic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_topic_quizzes_topic ON public.topic_quizzes USING btree (topic);

--
-- Name: ix_user_content_status_exclusion; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_content_status_exclusion ON public.user_content_status USING btree (user_id, content_id, is_hidden, is_saved, status);

--
-- Name: ix_user_content_status_user_has_note; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_content_status_user_has_note ON public.user_content_status USING btree (user_id, note_updated_at) WHERE ((note_text IS NOT NULL) AND (note_text <> ''::text));

--
-- Name: ix_user_content_status_user_liked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_content_status_user_liked ON public.user_content_status USING btree (user_id, is_liked);

--
-- Name: ix_user_content_status_user_saved; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_content_status_user_saved ON public.user_content_status USING btree (user_id, is_saved);

--
-- Name: ix_user_content_status_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_content_status_user_status ON public.user_content_status USING btree (user_id, status);

--
-- Name: ix_user_letter_progress_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_letter_progress_user_status ON public.user_letter_progress USING btree (user_id, status);

--
-- Name: ix_user_topic_profiles_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_topic_profiles_user_id ON public.user_topic_profiles USING btree (user_id);

--
-- Name: ix_user_topic_progress_topic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_topic_progress_topic ON public.user_topic_progress USING btree (topic);

--
-- Name: ix_user_topic_progress_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_topic_progress_user_id ON public.user_topic_progress USING btree (user_id);

--
-- Name: ix_utp_unique_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_utp_unique_entity ON public.user_topic_profiles USING btree (user_id, canonical_name) WHERE (canonical_name IS NOT NULL);

--
-- Name: ix_veille_configs_next_scheduled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_veille_configs_next_scheduled ON public.veille_configs USING btree (next_scheduled_at) WHERE ((status)::text = 'active'::text);

--
-- Name: ix_veille_configs_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_veille_configs_user_id ON public.veille_configs USING btree (user_id);

--
-- Name: ix_veille_deliveries_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_veille_deliveries_state ON public.veille_deliveries USING btree (generation_state);

--
-- Name: ix_veille_deliveries_target_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_veille_deliveries_target_date ON public.veille_deliveries USING btree (target_date);

--
-- Name: ix_veille_sources_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_veille_sources_source_id ON public.veille_sources USING btree (source_id);

--
-- Name: ix_waitlist_entries_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_waitlist_entries_email ON public.waitlist_entries USING btree (email);

--
-- Name: ix_waitlist_survey_entry_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_waitlist_survey_entry_id ON public.waitlist_survey_responses USING btree (waitlist_entry_id);

--
-- Name: ix_well_informed_ratings_submitted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_well_informed_ratings_submitted_at ON public.user_well_informed_ratings USING btree (submitted_at);

--
-- Name: ix_well_informed_ratings_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_well_informed_ratings_user_id ON public.user_well_informed_ratings USING btree (user_id);

--
-- Name: nps_responses_campaign_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nps_responses_campaign_idx ON public.nps_responses USING btree (campaign_id);

--
-- Name: nps_responses_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nps_responses_created_at_idx ON public.nps_responses USING btree (created_at DESC);

--
-- Name: uq_daily_top3_user_rank_day; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_daily_top3_user_rank_day ON public.daily_top3 USING btree (user_id, rank, date((generated_at AT TIME ZONE 'UTC'::text)));

--
-- Name: uq_veille_configs_user_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_veille_configs_user_active ON public.veille_configs USING btree (user_id) WHERE ((status)::text = 'active'::text);

--
-- Name: nps_responses nps_responses_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER nps_responses_set_updated_at BEFORE UPDATE ON public.nps_responses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

--
-- Name: collections trigger_collections_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_collections_updated_at BEFORE UPDATE ON public.collections FOR EACH ROW EXECUTE FUNCTION public.update_collections_updated_at();

--
-- Name: article_feedback article_feedback_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_feedback
    ADD CONSTRAINT article_feedback_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: classification_queue classification_queue_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classification_queue
    ADD CONSTRAINT classification_queue_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: collection_items collection_items_collection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_items
    ADD CONSTRAINT collection_items_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;

--
-- Name: collection_items collection_items_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_items
    ADD CONSTRAINT collection_items_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: contents contents_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contents
    ADD CONSTRAINT contents_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE CASCADE;

--
-- Name: curation_annotations curation_annotations_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curation_annotations
    ADD CONSTRAINT curation_annotations_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: daily_top3 daily_top3_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_top3
    ADD CONSTRAINT daily_top3_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: nps_responses nps_responses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

--
-- Name: perspective_analyses perspective_analyses_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.perspective_analyses
    ADD CONSTRAINT perspective_analyses_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: serene_reports serene_reports_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.serene_reports
    ADD CONSTRAINT serene_reports_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: user_content_status user_content_status_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_content_status
    ADD CONSTRAINT user_content_status_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.contents(id) ON DELETE CASCADE;

--
-- Name: user_interests user_interests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interests
    ADD CONSTRAINT user_interests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_letter_progress user_letter_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_letter_progress
    ADD CONSTRAINT user_letter_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_notification_preferences user_notification_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_preferences
    ADD CONSTRAINT user_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_personalization user_personalization_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_personalization
    ADD CONSTRAINT user_personalization_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_sources user_sources_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sources
    ADD CONSTRAINT user_sources_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE CASCADE;

--
-- Name: user_subtopics user_subtopics_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subtopics
    ADD CONSTRAINT user_subtopics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: user_topic_profiles user_topic_profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_topic_profiles
    ADD CONSTRAINT user_topic_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: veille_configs veille_configs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_configs
    ADD CONSTRAINT veille_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id) ON DELETE CASCADE;

--
-- Name: veille_deliveries veille_deliveries_veille_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_deliveries
    ADD CONSTRAINT veille_deliveries_veille_config_id_fkey FOREIGN KEY (veille_config_id) REFERENCES public.veille_configs(id) ON DELETE CASCADE;

--
-- Name: veille_sources veille_sources_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_sources
    ADD CONSTRAINT veille_sources_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id) ON DELETE RESTRICT;

--
-- Name: veille_sources veille_sources_veille_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_sources
    ADD CONSTRAINT veille_sources_veille_config_id_fkey FOREIGN KEY (veille_config_id) REFERENCES public.veille_configs(id) ON DELETE CASCADE;

--
-- Name: veille_topics veille_topics_veille_config_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.veille_topics
    ADD CONSTRAINT veille_topics_veille_config_id_fkey FOREIGN KEY (veille_config_id) REFERENCES public.veille_configs(id) ON DELETE CASCADE;

--
-- Name: waitlist_survey_responses waitlist_survey_responses_waitlist_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.waitlist_survey_responses
    ADD CONSTRAINT waitlist_survey_responses_waitlist_entry_id_fkey FOREIGN KEY (waitlist_entry_id) REFERENCES public.waitlist_entries(id) ON DELETE CASCADE;

--
-- Name: user_topic_profiles Users can manage their own topic profiles; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: alembic_version; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: analytics_events; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: app_config; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: app_config app_config readable by authenticated; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: contents; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: contents contents_select_authenticated; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: nps_responses; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: source_search_logs; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: sources; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: sources sources_select_authenticated; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_content_status; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_content_status user_content_status_delete_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_content_status user_content_status_insert_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_content_status user_content_status_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_content_status user_content_status_update_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_interests; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_interests user_interests_delete_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_interests user_interests_insert_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_interests user_interests_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_letter_progress; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_notification_preferences; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_preferences; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_preferences user_preferences_delete_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_preferences user_preferences_insert_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_preferences user_preferences_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_profiles user_profiles_insert_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_profiles user_profiles_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_profiles user_profiles_update_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_sources; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_sources user_sources_delete_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_sources user_sources_insert_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_sources user_sources_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_sources user_sources_update_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_streaks; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_streaks user_streaks_select_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_streaks user_streaks_update_own; Type: POLICY; Schema: public; Owner: -
--

--
-- Name: user_topic_profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: user_well_informed_ratings; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: veille_configs; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: veille_deliveries; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: veille_sources; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: veille_topics; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: waitlist_entries; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- Name: waitlist_survey_responses; Type: ROW SECURITY; Schema: public; Owner: -
--

--
-- PostgreSQL database dump complete
--

\unrestrict jf8K4albLtfvG21T3Ds57jSrwBEFDBbL8IdtDJoU6RcU58WoQhkdax4gXbstdT2

