-- Sanitized prod schema snapshot — see sanitize.py for what was stripped.
-- Generated by packages/api/alembic/baseline/sanitize.py

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

CREATE SCHEMA IF NOT EXISTS "public";

CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."update_collections_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS "public"."analytics_events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "event_type" character varying(50) NOT NULL,
    "event_data" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "device_id" character varying(255),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."app_config" (
    "key" "text" NOT NULL,
    "value" "jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."article_feedback" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "sentiment" character varying(10) NOT NULL,
    "reasons" "text"[],
    "comment" "text",
    "digest_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."classification_queue" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content_id" "uuid" NOT NULL,
    "status" character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    "priority" integer DEFAULT 0 NOT NULL,
    "retry_count" integer DEFAULT 0 NOT NULL,
    "error_message" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "processed_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "public"."collection_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "collection_id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."collections" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" character varying(100) NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_default" boolean DEFAULT false NOT NULL,
    "is_liked_collection" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."contents" (
    "id" "uuid" NOT NULL,
    "source_id" "uuid" NOT NULL,
    "title" character varying(500) NOT NULL,
    "url" "text" NOT NULL,
    "thumbnail_url" "text",
    "description" "text",
    "published_at" timestamp with time zone NOT NULL,
    "duration_seconds" integer,
    "content_type" character varying(20) NOT NULL,
    "guid" character varying(500) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "cluster_id" "uuid",
    "html_content" "text",
    "audio_url" "text",
    "topics" "text"[],
    "theme" character varying(50),
    "is_paid" boolean DEFAULT false,
    "content_quality" character varying(20) DEFAULT NULL::character varying,
    "extraction_attempted_at" timestamp with time zone,
    "is_serene" boolean,
    "entities" "text"[]
);

CREATE TABLE IF NOT EXISTS "public"."curation_annotations" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "feed_date" "date" NOT NULL,
    "label" character varying(10) NOT NULL,
    "note" "text",
    "annotated_by" character varying(50) DEFAULT 'admin'::character varying NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    CONSTRAINT "ck_curation_label" CHECK ((("label")::"text" = ANY ((ARRAY['good'::character varying, 'bad'::character varying, 'missing'::character varying])::"text"[])))
);

CREATE TABLE IF NOT EXISTS "public"."daily_digest" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "target_date" "date" NOT NULL,
    "items" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "generated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "mode" character varying(30) DEFAULT 'pour_vous'::character varying,
    "format_version" character varying(20) DEFAULT 'flat_v1'::character varying,
    "is_serene" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."daily_top3" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "rank" integer NOT NULL,
    "top3_reason" character varying(100) NOT NULL,
    "consumed" boolean DEFAULT false NOT NULL,
    "generated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "daily_top3_rank_check" CHECK ((("rank" >= 1) AND ("rank" <= 3)))
);

CREATE TABLE IF NOT EXISTS "public"."digest_completions" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "target_date" "date" NOT NULL,
    "completed_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "articles_read" integer DEFAULT 0 NOT NULL,
    "articles_saved" integer DEFAULT 0 NOT NULL,
    "articles_dismissed" integer DEFAULT 0 NOT NULL,
    "closure_time_seconds" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."digest_generation_state" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "target_date" "date" NOT NULL,
    "is_serene" boolean DEFAULT false NOT NULL,
    "status" character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    "attempts" integer DEFAULT 0 NOT NULL,
    "last_error" "text",
    "started_at" timestamp with time zone,
    "finished_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."editorial_highlights_history" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "kind" character varying(20) NOT NULL,
    "content_id" "uuid" NOT NULL,
    "target_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."failed_source_attempts" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "input_text" character varying(500) NOT NULL,
    "input_type" character varying(20) NOT NULL,
    "endpoint" character varying(20) NOT NULL,
    "error_message" "text",
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."nps_responses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "score" smallint NOT NULL,
    "comment" "text",
    "campaign_id" "text" DEFAULT 'default'::"text" NOT NULL,
    "source" "text" DEFAULT 'email'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "nps_responses_score_check" CHECK ((("score" >= 0) AND ("score" <= 10)))
);

COMMENT ON TABLE "public"."nps_responses" IS 'Réponses NPS récoltées via emails Brevo. Ecriture exclusive via edge function nps.';

CREATE TABLE IF NOT EXISTS "public"."perspective_analyses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content_id" "uuid" NOT NULL,
    "analysis_text" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."serene_reports" (
    "id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."source_search_cache" (
    "query_hash" character varying(64) NOT NULL,
    "query_raw" "text" NOT NULL,
    "payload" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expires_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."source_search_logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "query_raw" character varying(500) NOT NULL,
    "query_normalized" character varying(500) NOT NULL,
    "content_type" character varying(20),
    "expand" boolean DEFAULT false NOT NULL,
    "layers_called" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "result_count" integer DEFAULT 0 NOT NULL,
    "top_results" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "latency_ms" integer DEFAULT 0 NOT NULL,
    "cache_hit" boolean DEFAULT false NOT NULL,
    "abandoned" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."sources" (
    "id" "uuid" NOT NULL,
    "name" character varying(200) NOT NULL,
    "url" "text" NOT NULL,
    "feed_url" "text" NOT NULL,
    "type" character varying(20) NOT NULL,
    "theme" character varying(50) NOT NULL,
    "description" "text",
    "logo_url" "text",
    "is_curated" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "last_synced_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL,
    "bias_stance" character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    "reliability_score" character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    "bias_origin" character varying(20) DEFAULT 'unknown'::character varying NOT NULL,
    "score_independence" double precision,
    "score_rigor" double precision,
    "score_ux" double precision,
    "granular_topics" "text"[],
    "une_feed_url" "text",
    "secondary_themes" "text"[],
    "paywall_config" "jsonb",
    "source_tier" character varying(20) DEFAULT 'mainstream'::character varying NOT NULL,
    "tone" character varying(20),
    "serein_default" boolean DEFAULT false NOT NULL,
    "is_pepite_recommendation" boolean DEFAULT false NOT NULL,
    "pepite_for_themes" "text"[],
    "editorial_note" "text",
    CONSTRAINT "ck_source_theme_valid" CHECK ((("theme")::"text" = ANY ((ARRAY['tech'::character varying, 'society'::character varying, 'environment'::character varying, 'economy'::character varying, 'politics'::character varying, 'culture'::character varying, 'science'::character varying, 'international'::character varying, 'custom'::character varying])::"text"[])))
);

CREATE TABLE IF NOT EXISTS "public"."topic_quizzes" (
    "id" "uuid" NOT NULL,
    "topic" character varying(100) NOT NULL,
    "question" "text" NOT NULL,
    "options" "jsonb" NOT NULL,
    "correct_answer" integer NOT NULL,
    "difficulty" integer DEFAULT 1 NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_content_status" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content_id" "uuid" NOT NULL,
    "status" character varying(20) NOT NULL,
    "seen_at" timestamp with time zone,
    "time_spent_seconds" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "is_saved" boolean DEFAULT false NOT NULL,
    "is_hidden" boolean DEFAULT false NOT NULL,
    "hidden_reason" character varying,
    "saved_at" timestamp with time zone,
    "is_liked" boolean DEFAULT false NOT NULL,
    "liked_at" timestamp with time zone,
    "note_text" "text",
    "note_updated_at" timestamp with time zone,
    "last_impressed_at" timestamp with time zone,
    "manually_impressed" boolean DEFAULT false NOT NULL,
    "reading_progress" smallint DEFAULT '0'::smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_entity_preferences" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "entity_canonical" "text" NOT NULL,
    "preference" character varying(10) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_interests" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "interest_slug" character varying(50) NOT NULL,
    "weight" double precision NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_notification_preferences" (
    "user_id" "uuid" NOT NULL,
    "push_enabled" boolean DEFAULT false NOT NULL,
    "preset" "text" DEFAULT 'minimaliste'::"text" NOT NULL,
    "time_slot" "text" DEFAULT 'morning'::"text" NOT NULL,
    "timezone" "text" DEFAULT 'Europe/Paris'::"text" NOT NULL,
    "refusal_count" integer DEFAULT 0 NOT NULL,
    "last_refusal_at" timestamp with time zone,
    "last_renudge_at" timestamp with time zone,
    "renudge_shown_count" integer DEFAULT 0 NOT NULL,
    "modal_seen" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "user_notif_prefs_preset_check" CHECK (("preset" = ANY (ARRAY['minimaliste'::"text", 'curieux'::"text"]))),
    CONSTRAINT "user_notif_prefs_time_slot_check" CHECK (("time_slot" = ANY (ARRAY['morning'::"text", 'evening'::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."user_personalization" (
    "user_id" "uuid" NOT NULL,
    "muted_sources" "uuid"[] DEFAULT '{}'::"uuid"[] NOT NULL,
    "muted_themes" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "muted_topics" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "muted_content_types" "text"[] DEFAULT '{}'::"text"[],
    "hide_paid_content" boolean DEFAULT true,
    "pepite_carousel_dismissed_at" timestamp with time zone,
    "pepite_carousel_last_shown_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "public"."user_preferences" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "preference_key" character varying(50) NOT NULL,
    "preference_value" character varying(100) NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "display_name" character varying(100),
    "age_range" character varying(10),
    "gender" character varying(20),
    "onboarding_completed" boolean NOT NULL,
    "gamification_enabled" boolean NOT NULL,
    "weekly_goal" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_sources" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "source_id" "uuid" NOT NULL,
    "is_custom" boolean NOT NULL,
    "added_at" timestamp with time zone NOT NULL,
    "priority_multiplier" double precision DEFAULT '1'::double precision NOT NULL,
    "has_subscription" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_streaks" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "current_streak" integer NOT NULL,
    "longest_streak" integer NOT NULL,
    "last_activity_date" "date",
    "weekly_count" integer NOT NULL,
    "week_start" "date",
    "updated_at" timestamp with time zone NOT NULL,
    "closure_streak" integer DEFAULT 0 NOT NULL,
    "longest_closure_streak" integer DEFAULT 0 NOT NULL,
    "last_closure_date" "date"
);

CREATE TABLE IF NOT EXISTS "public"."user_subscriptions" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "revenuecat_user_id" character varying(200),
    "status" character varying(20) NOT NULL,
    "product_id" character varying(100),
    "trial_start" timestamp with time zone NOT NULL,
    "trial_end" timestamp with time zone NOT NULL,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_subtopics" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "topic_slug" character varying(50) NOT NULL,
    "weight" double precision DEFAULT 1.0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_topic_profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "topic_name" character varying(200) NOT NULL,
    "slug_parent" character varying(50) NOT NULL,
    "keywords" "text"[],
    "intent_description" "text",
    "source_type" character varying(20) DEFAULT 'explicit'::character varying NOT NULL,
    "priority_multiplier" double precision DEFAULT 1.0 NOT NULL,
    "composite_score" double precision DEFAULT 0.0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "entity_type" character varying(20) DEFAULT NULL::character varying,
    "canonical_name" character varying(200) DEFAULT NULL::character varying,
    "excluded_from_serein" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_topic_progress" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "topic" character varying(100) NOT NULL,
    "level" integer DEFAULT 1 NOT NULL,
    "points" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_well_informed_ratings" (
    "id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "score" integer NOT NULL,
    "context" character varying(32) DEFAULT 'digest_inline'::character varying NOT NULL,
    "device_id" character varying(255),
    "submitted_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ck_well_informed_ratings_score_range" CHECK ((("score" >= 1) AND ("score" <= 10)))
);

CREATE TABLE IF NOT EXISTS "public"."waitlist_entries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" character varying(255) NOT NULL,
    "source" character varying(50) DEFAULT 'landing'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "utm_source" character varying(100),
    "utm_medium" character varying(100),
    "utm_campaign" character varying(100)
);

CREATE TABLE IF NOT EXISTS "public"."waitlist_survey_responses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "waitlist_entry_id" "uuid" NOT NULL,
    "info_source" character varying(100) NOT NULL,
    "main_pain" character varying(100) NOT NULL,
    "pain_detail" "text",
    "willingness" character varying(100) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE ONLY "public"."analytics_events"
    ADD CONSTRAINT "analytics_events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."app_config"
    ADD CONSTRAINT "app_config_pkey" PRIMARY KEY ("key");

ALTER TABLE ONLY "public"."article_feedback"
    ADD CONSTRAINT "article_feedback_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."classification_queue"
    ADD CONSTRAINT "classification_queue_content_id_key" UNIQUE ("content_id");

ALTER TABLE ONLY "public"."classification_queue"
    ADD CONSTRAINT "classification_queue_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."collection_items"
    ADD CONSTRAINT "collection_items_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "collections_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."contents"
    ADD CONSTRAINT "contents_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."curation_annotations"
    ADD CONSTRAINT "curation_annotations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."daily_digest"
    ADD CONSTRAINT "daily_digest_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."daily_top3"
    ADD CONSTRAINT "daily_top3_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."digest_completions"
    ADD CONSTRAINT "digest_completions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."digest_generation_state"
    ADD CONSTRAINT "digest_generation_state_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."editorial_highlights_history"
    ADD CONSTRAINT "editorial_highlights_history_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."failed_source_attempts"
    ADD CONSTRAINT "failed_source_attempts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."nps_responses"
    ADD CONSTRAINT "nps_responses_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."nps_responses"
    ADD CONSTRAINT "nps_responses_user_campaign_unique" UNIQUE ("user_id", "campaign_id");

ALTER TABLE ONLY "public"."perspective_analyses"
    ADD CONSTRAINT "perspective_analyses_content_id_key" UNIQUE ("content_id");

ALTER TABLE ONLY "public"."perspective_analyses"
    ADD CONSTRAINT "perspective_analyses_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."serene_reports"
    ADD CONSTRAINT "serene_reports_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."source_search_cache"
    ADD CONSTRAINT "source_search_cache_pkey" PRIMARY KEY ("query_hash");

ALTER TABLE ONLY "public"."source_search_logs"
    ADD CONSTRAINT "source_search_logs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sources"
    ADD CONSTRAINT "sources_feed_url_key" UNIQUE ("feed_url");

ALTER TABLE ONLY "public"."sources"
    ADD CONSTRAINT "sources_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."topic_quizzes"
    ADD CONSTRAINT "topic_quizzes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."article_feedback"
    ADD CONSTRAINT "uq_article_feedback_user_content" UNIQUE ("user_id", "content_id");

ALTER TABLE ONLY "public"."collection_items"
    ADD CONSTRAINT "uq_collection_item" UNIQUE ("collection_id", "content_id");

ALTER TABLE ONLY "public"."collections"
    ADD CONSTRAINT "uq_collection_user_name" UNIQUE ("user_id", "name");

ALTER TABLE ONLY "public"."curation_annotations"
    ADD CONSTRAINT "uq_curation_user_content_date" UNIQUE ("user_id", "content_id", "feed_date");

ALTER TABLE ONLY "public"."daily_digest"
    ADD CONSTRAINT "uq_daily_digest_user_date_serene" UNIQUE ("user_id", "target_date", "is_serene");

ALTER TABLE ONLY "public"."digest_completions"
    ADD CONSTRAINT "uq_digest_completions_user_date" UNIQUE ("user_id", "target_date");

ALTER TABLE ONLY "public"."digest_generation_state"
    ADD CONSTRAINT "uq_digest_generation_state_user_date_variant" UNIQUE ("user_id", "target_date", "is_serene");

ALTER TABLE ONLY "public"."serene_reports"
    ADD CONSTRAINT "uq_serene_report_user_content" UNIQUE ("user_id", "content_id");

ALTER TABLE ONLY "public"."user_content_status"
    ADD CONSTRAINT "uq_user_content_status_user_content" UNIQUE ("user_id", "content_id");

ALTER TABLE ONLY "public"."user_entity_preferences"
    ADD CONSTRAINT "uq_user_entity_pref_user_entity" UNIQUE ("user_id", "entity_canonical");

ALTER TABLE ONLY "public"."user_sources"
    ADD CONSTRAINT "uq_user_sources_user_source" UNIQUE ("user_id", "source_id");

ALTER TABLE ONLY "public"."user_topic_progress"
    ADD CONSTRAINT "uq_user_topic_progress_user_topic" UNIQUE ("user_id", "topic");

ALTER TABLE ONLY "public"."user_content_status"
    ADD CONSTRAINT "user_content_status_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_entity_preferences"
    ADD CONSTRAINT "user_entity_preferences_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_interests"
    ADD CONSTRAINT "user_interests_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_notification_preferences"
    ADD CONSTRAINT "user_notification_preferences_pkey" PRIMARY KEY ("user_id");

ALTER TABLE ONLY "public"."user_personalization"
    ADD CONSTRAINT "user_personalization_pkey" PRIMARY KEY ("user_id");

ALTER TABLE ONLY "public"."user_preferences"
    ADD CONSTRAINT "user_preferences_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."user_sources"
    ADD CONSTRAINT "user_sources_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_streaks"
    ADD CONSTRAINT "user_streaks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_streaks"
    ADD CONSTRAINT "user_streaks_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_subscriptions"
    ADD CONSTRAINT "user_subscriptions_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."user_subtopics"
    ADD CONSTRAINT "user_subtopics_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_topic_profiles"
    ADD CONSTRAINT "user_topic_profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_topic_progress"
    ADD CONSTRAINT "user_topic_progress_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_well_informed_ratings"
    ADD CONSTRAINT "user_well_informed_ratings_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."waitlist_entries"
    ADD CONSTRAINT "waitlist_entries_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."waitlist_survey_responses"
    ADD CONSTRAINT "waitlist_survey_responses_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_entity_prefs_user_mute" ON "public"."user_entity_preferences" USING "btree" ("user_id") WHERE (("preference")::"text" = 'mute'::"text");

CREATE INDEX "idx_entity_prefs_user_pref" ON "public"."user_entity_preferences" USING "btree" ("user_id", "preference");

CREATE INDEX "idx_queue_priority" ON "public"."classification_queue" USING "btree" ("priority" DESC, "created_at");

CREATE INDEX "idx_queue_status_created" ON "public"."classification_queue" USING "btree" ("status", "created_at");

CREATE INDEX "ix_analytics_events_created_at" ON "public"."analytics_events" USING "btree" ("created_at");

CREATE INDEX "ix_analytics_events_event_type" ON "public"."analytics_events" USING "btree" ("event_type");

CREATE INDEX "ix_analytics_events_user_id" ON "public"."analytics_events" USING "btree" ("user_id");

CREATE INDEX "ix_article_feedback_content_id" ON "public"."article_feedback" USING "btree" ("content_id");

CREATE INDEX "ix_collection_items_collection" ON "public"."collection_items" USING "btree" ("collection_id");

CREATE INDEX "ix_collection_items_content" ON "public"."collection_items" USING "btree" ("content_id");

CREATE INDEX "ix_collections_user_id" ON "public"."collections" USING "btree" ("user_id");

CREATE INDEX "ix_contents_cluster_id" ON "public"."contents" USING "btree" ("cluster_id");

CREATE INDEX "ix_contents_curated_published" ON "public"."contents" USING "btree" ("published_at" DESC, "source_id");

CREATE INDEX "ix_contents_entities" ON "public"."contents" USING "gin" ("entities");

CREATE INDEX "ix_contents_guid" ON "public"."contents" USING "btree" ("guid");

CREATE INDEX "ix_contents_published_at" ON "public"."contents" USING "btree" ("published_at");

CREATE INDEX "ix_contents_source_id" ON "public"."contents" USING "btree" ("source_id");

CREATE INDEX "ix_contents_source_published" ON "public"."contents" USING "btree" ("source_id", "published_at" DESC);

CREATE INDEX "ix_contents_theme_published" ON "public"."contents" USING "btree" ("theme", "published_at" DESC);

CREATE INDEX "ix_curation_annotations_feed_date" ON "public"."curation_annotations" USING "btree" ("feed_date");

CREATE INDEX "ix_curation_annotations_user_id" ON "public"."curation_annotations" USING "btree" ("user_id");

CREATE INDEX "ix_daily_digest_generated_at" ON "public"."daily_digest" USING "btree" ("generated_at");

CREATE INDEX "ix_daily_digest_target_date" ON "public"."daily_digest" USING "btree" ("target_date");

CREATE INDEX "ix_daily_digest_user_id" ON "public"."daily_digest" USING "btree" ("user_id");

CREATE INDEX "ix_daily_top3_user_date" ON "public"."daily_top3" USING "btree" ("user_id", "generated_at");

CREATE INDEX "ix_daily_top3_user_id" ON "public"."daily_top3" USING "btree" ("user_id");

CREATE INDEX "ix_digest_completions_completed_at" ON "public"."digest_completions" USING "btree" ("completed_at");

CREATE INDEX "ix_digest_completions_target_date" ON "public"."digest_completions" USING "btree" ("target_date");

CREATE INDEX "ix_digest_completions_user_id" ON "public"."digest_completions" USING "btree" ("user_id");

CREATE INDEX "ix_digest_generation_state_status" ON "public"."digest_generation_state" USING "btree" ("status");

CREATE INDEX "ix_digest_generation_state_target_date" ON "public"."digest_generation_state" USING "btree" ("target_date");

CREATE INDEX "ix_editorial_highlights_history_content_id" ON "public"."editorial_highlights_history" USING "btree" ("content_id");

CREATE INDEX "ix_editorial_highlights_history_kind_date" ON "public"."editorial_highlights_history" USING "btree" ("kind", "target_date");

CREATE INDEX "ix_failed_source_attempts_created_at" ON "public"."failed_source_attempts" USING "btree" ("created_at");

CREATE INDEX "ix_failed_source_attempts_input_text" ON "public"."failed_source_attempts" USING "btree" ("input_text");

CREATE INDEX "ix_failed_source_attempts_user_id" ON "public"."failed_source_attempts" USING "btree" ("user_id");

CREATE INDEX "ix_perspective_analyses_content_id" ON "public"."perspective_analyses" USING "btree" ("content_id");

CREATE INDEX "ix_serene_reports_content_id" ON "public"."serene_reports" USING "btree" ("content_id");

CREATE INDEX "ix_source_search_cache_expires_at" ON "public"."source_search_cache" USING "btree" ("expires_at");

CREATE INDEX "ix_source_search_logs_created_at" ON "public"."source_search_logs" USING "btree" ("created_at");

CREATE INDEX "ix_source_search_logs_query_normalized" ON "public"."source_search_logs" USING "btree" ("query_normalized");

CREATE INDEX "ix_source_search_logs_user_id" ON "public"."source_search_logs" USING "btree" ("user_id");

CREATE INDEX "ix_sources_is_active" ON "public"."sources" USING "btree" ("is_active");

CREATE INDEX "ix_sources_is_curated" ON "public"."sources" USING "btree" ("is_curated");

CREATE INDEX "ix_sources_is_pepite_recommendation" ON "public"."sources" USING "btree" ("is_pepite_recommendation");

CREATE INDEX "ix_sources_secondary_themes" ON "public"."sources" USING "gin" ("secondary_themes");

CREATE INDEX "ix_sources_theme" ON "public"."sources" USING "btree" ("theme");

CREATE INDEX "ix_topic_quizzes_topic" ON "public"."topic_quizzes" USING "btree" ("topic");

CREATE INDEX "ix_user_content_status_exclusion" ON "public"."user_content_status" USING "btree" ("user_id", "content_id", "is_hidden", "is_saved", "status");

CREATE INDEX "ix_user_content_status_user_has_note" ON "public"."user_content_status" USING "btree" ("user_id", "note_updated_at") WHERE (("note_text" IS NOT NULL) AND ("note_text" <> ''::"text"));

CREATE INDEX "ix_user_content_status_user_liked" ON "public"."user_content_status" USING "btree" ("user_id", "is_liked");

CREATE INDEX "ix_user_content_status_user_saved" ON "public"."user_content_status" USING "btree" ("user_id", "is_saved");

CREATE INDEX "ix_user_content_status_user_status" ON "public"."user_content_status" USING "btree" ("user_id", "status");

CREATE INDEX "ix_user_topic_profiles_user_id" ON "public"."user_topic_profiles" USING "btree" ("user_id");

CREATE INDEX "ix_user_topic_progress_topic" ON "public"."user_topic_progress" USING "btree" ("topic");

CREATE INDEX "ix_user_topic_progress_user_id" ON "public"."user_topic_progress" USING "btree" ("user_id");

CREATE UNIQUE INDEX "ix_utp_unique_entity" ON "public"."user_topic_profiles" USING "btree" ("user_id", "canonical_name") WHERE ("canonical_name" IS NOT NULL);

CREATE INDEX "ix_waitlist_entries_email" ON "public"."waitlist_entries" USING "btree" ("email");

CREATE INDEX "ix_waitlist_survey_entry_id" ON "public"."waitlist_survey_responses" USING "btree" ("waitlist_entry_id");

CREATE INDEX "ix_well_informed_ratings_submitted_at" ON "public"."user_well_informed_ratings" USING "btree" ("submitted_at");

CREATE INDEX "ix_well_informed_ratings_user_id" ON "public"."user_well_informed_ratings" USING "btree" ("user_id");

CREATE INDEX "nps_responses_campaign_idx" ON "public"."nps_responses" USING "btree" ("campaign_id");

CREATE INDEX "nps_responses_created_at_idx" ON "public"."nps_responses" USING "btree" ("created_at" DESC);

CREATE UNIQUE INDEX "uq_daily_top3_user_rank_day" ON "public"."daily_top3" USING "btree" ("user_id", "rank", "date"(("generated_at" AT TIME ZONE 'UTC'::"text")));

CREATE OR REPLACE TRIGGER "nps_responses_set_updated_at" BEFORE UPDATE ON "public"."nps_responses" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE OR REPLACE TRIGGER "trigger_collections_updated_at" BEFORE UPDATE ON "public"."collections" FOR EACH ROW EXECUTE FUNCTION "public"."update_collections_updated_at"();

ALTER TABLE ONLY "public"."article_feedback"
    ADD CONSTRAINT "article_feedback_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."classification_queue"
    ADD CONSTRAINT "classification_queue_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."collection_items"
    ADD CONSTRAINT "collection_items_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collections"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."collection_items"
    ADD CONSTRAINT "collection_items_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."contents"
    ADD CONSTRAINT "contents_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."curation_annotations"
    ADD CONSTRAINT "curation_annotations_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."daily_top3"
    ADD CONSTRAINT "daily_top3_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."perspective_analyses"
    ADD CONSTRAINT "perspective_analyses_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."serene_reports"
    ADD CONSTRAINT "serene_reports_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_content_status"
    ADD CONSTRAINT "user_content_status_content_id_fkey" FOREIGN KEY ("content_id") REFERENCES "public"."contents"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_interests"
    ADD CONSTRAINT "user_interests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_notification_preferences"
    ADD CONSTRAINT "user_notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_personalization"
    ADD CONSTRAINT "user_personalization_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_preferences"
    ADD CONSTRAINT "user_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_sources"
    ADD CONSTRAINT "user_sources_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_subtopics"
    ADD CONSTRAINT "user_subtopics_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_topic_profiles"
    ADD CONSTRAINT "user_topic_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."waitlist_survey_responses"
    ADD CONSTRAINT "waitlist_survey_responses_waitlist_entry_id_fkey" FOREIGN KEY ("waitlist_entry_id") REFERENCES "public"."waitlist_entries"("id") ON DELETE CASCADE;

