import 'package:flutter/material.dart';

import '../../../config/theme.dart';

/// Editorial intro text displayed above article cards for each subject (N1).
///
/// Shows 2-3 sentences of editorial context generated by LLM.
class IntroText extends StatelessWidget {
  final String text;

  const IntroText({super.key, required this.text});

  @override
  Widget build(BuildContext context) {
    final colors = context.facteurColors;
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 12),
      child: Text(
        text,
        style: FacteurTypography.bodyLarge(colors.textPrimary),
      ),
    );
  }
}
