"""Add closure streak columns to user_streaks

Revision ID: 4d497ce7bcc2
Revises: 752ae6586a6f
Create Date: 2026-02-02 01:14:00.869847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d497ce7bcc2'
down_revision: Union[str, Sequence[str], None] = '752ae6586a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('analytics_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index(op.f('idx_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('idx_analytics_events_type_time'), table_name='analytics_events')
    op.drop_index(op.f('idx_analytics_events_user_id'), table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index('idx_queue_priority', 'classification_queue', [sa.literal_column('priority DESC'), 'created_at'], unique=False)
    op.drop_index(op.f('ix_contents_entities'), table_name='contents', postgresql_using='gin')
    op.drop_index(op.f('ix_contents_topics'), table_name='contents', postgresql_using='gin')
    op.create_index('ix_contents_published_at', 'contents', ['published_at'], unique=False)
    op.create_index('ix_contents_source_id', 'contents', ['source_id'], unique=False)
    op.drop_column('contents', 'entities')
    op.drop_index(op.f('uq_daily_digest_user_date'), table_name='daily_digest')
    op.create_unique_constraint('uq_daily_digest_user_date', 'daily_digest', ['user_id', 'target_date'])
    op.create_index('ix_daily_digest_generated_at', 'daily_digest', ['generated_at'], unique=False)
    op.create_index('ix_daily_digest_target_date', 'daily_digest', ['target_date'], unique=False)
    op.create_index('ix_daily_digest_user_id', 'daily_digest', ['user_id'], unique=False)
    op.drop_index(op.f('uq_daily_top3_user_rank_day'), table_name='daily_top3')
    op.create_index('uq_daily_top3_user_rank_day', 'daily_top3', ['user_id', 'rank', sa.literal_column("date(generated_at AT TIME ZONE 'UTC')")], unique=True)
    op.create_foreign_key(None, 'daily_top3', 'contents', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_digest_completions_user_date'), table_name='digest_completions')
    op.create_unique_constraint('uq_digest_completions_user_date', 'digest_completions', ['user_id', 'target_date'])
    op.create_index('ix_digest_completions_completed_at', 'digest_completions', ['completed_at'], unique=False)
    op.create_index('ix_digest_completions_target_date', 'digest_completions', ['target_date'], unique=False)
    op.alter_column('topic_quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_user_content_status_user_saved', 'user_content_status', ['user_id', 'is_saved'], unique=False)
    op.create_index('ix_user_content_status_user_status', 'user_content_status', ['user_id', 'status'], unique=False)
    op.add_column('user_streaks', sa.Column('closure_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_streaks', sa.Column('longest_closure_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_streaks', sa.Column('last_closure_date', sa.Date(), nullable=True))
    op.drop_constraint(op.f('uq_user_subtopics_user_topic'), 'user_subtopics', type_='unique')
    op.alter_column('user_topic_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user_topic_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_topic_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_topic_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_subtopics_user_topic'), 'user_subtopics', ['user_id', 'topic_slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_streaks', 'last_closure_date')
    op.drop_column('user_streaks', 'longest_closure_streak')
    op.drop_column('user_streaks', 'closure_streak')
    op.drop_index('ix_user_content_status_user_status', table_name='user_content_status')
    op.drop_index('ix_user_content_status_user_saved', table_name='user_content_status')
    op.alter_column('topic_quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_digest_completions_target_date', table_name='digest_completions')
    op.drop_index('ix_digest_completions_completed_at', table_name='digest_completions')
    op.drop_constraint('uq_digest_completions_user_date', 'digest_completions', type_='unique')
    op.create_index(op.f('uq_digest_completions_user_date'), 'digest_completions', ['user_id', 'target_date'], unique=True)
    op.drop_constraint(None, 'daily_top3', type_='foreignkey')
    op.drop_index('uq_daily_top3_user_rank_day', table_name='daily_top3')
    op.create_index(op.f('uq_daily_top3_user_rank_day'), 'daily_top3', ['user_id', 'rank', sa.literal_column("date((generated_at AT TIME ZONE 'UTC'::text))")], unique=True)
    op.drop_index('ix_daily_digest_user_id', table_name='daily_digest')
    op.drop_index('ix_daily_digest_target_date', table_name='daily_digest')
    op.drop_index('ix_daily_digest_generated_at', table_name='daily_digest')
    op.drop_constraint('uq_daily_digest_user_date', 'daily_digest', type_='unique')
    op.create_index(op.f('uq_daily_digest_user_date'), 'daily_digest', ['user_id', 'target_date'], unique=True)
    op.add_column('contents', sa.Column('entities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_index('ix_contents_source_id', table_name='contents')
    op.drop_index('ix_contents_published_at', table_name='contents')
    op.create_index(op.f('ix_contents_topics'), 'contents', ['topics'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_contents_entities'), 'contents', ['entities'], unique=False, postgresql_using='gin')
    op.drop_index('idx_queue_priority', table_name='classification_queue')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.create_index(op.f('idx_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('idx_analytics_events_type_time'), 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.alter_column('analytics_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analytics_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
