"""add_bias_and_reliability_to_source_v2

Revision ID: 4d7188dfeefd
Revises: e238c370940c
Create Date: 2026-01-11 23:17:13.183800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7188dfeefd'
down_revision: Union[str, Sequence[str], None] = 'e238c370940c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('bias_stance', sa.Enum('left', 'center-left', 'center', 'center-right', 'right', 'alternative', 'specialized', 'unknown', name='biasstance', native_enum=False, length=20), server_default='unknown', nullable=False))
    op.add_column('sources', sa.Column('reliability_score', sa.Enum('low', 'mixed', 'high', 'unknown', name='reliabilityscore', native_enum=False, length=20), server_default='unknown', nullable=False))
    op.add_column('sources', sa.Column('bias_origin', sa.Enum('external-db', 'curated', 'llm', 'unknown', name='biasorigin', native_enum=False, length=20), server_default='unknown', nullable=False))
    op.add_column('user_content_status', sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_content_status', 'saved_at')
    op.drop_column('sources', 'bias_origin')
    op.drop_column('sources', 'reliability_score')
    op.drop_column('sources', 'bias_stance')
    # ### end Alembic commands ###
