"""add hidden_reason to user_content_status

Revision ID: e238c370940c
Revises: e9ae8866ece2
Create Date: 2026-01-11 21:35:11.033389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e238c370940c'
down_revision: Union[str, Sequence[str], None] = 'e9ae8866ece2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_content_status', sa.Column('hidden_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_content_status', 'hidden_reason')
    # ### end Alembic commands ###
