"""add_cluster_id_to_content

Revision ID: e5241a22714f
Revises: 4d7188dfeefd
Create Date: 2026-01-11 23:24:31.504781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5241a22714f'
down_revision: Union[str, Sequence[str], None] = '4d7188dfeefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('cluster_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contents_cluster_id'), 'contents', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_cluster_id'), table_name='contents')
    op.drop_column('contents', 'cluster_id')
    # ### end Alembic commands ###
